In [171]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/anmolkumar/analytics-vidhya-loan-prediction/sample_submission.csv
/kaggle/input/datasets/anmolkumar/analytics-vidhya-loan-prediction/train.csv
/kaggle/input/datasets/anmolkumar/analytics-vidhya-loan-prediction/test.csv

In [172]:
import numpy as np
import pandas as pd

In [173]:
df = pd.read_csv(r"/kaggle/input/datasets/anmolkumar/analytics-vidhya-loan-prediction/train.csv")

In [174]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [176]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [177]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [178]:
df = df.drop(['Loan_ID'], axis=1)

In [179]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [180]:
df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [181]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [182]:
df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])

In [183]:
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])

In [184]:
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])

In [185]:
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].mean())

In [186]:
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median())

In [187]:
df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mode()[0])

In [188]:
df['Property_Area'].value_counts()

Property_Area
Semiurban    233
Urban        202
Rural        179
Name: count, dtype: int64

In [189]:
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})
df['Married'] = df['Married'].map({'Yes': 1, 'No': 0})
df['Self_Employed'] = df['Self_Employed'].map({'Yes': 1, 'No': 0})
df['Loan_Status'] = df['Loan_Status'].map({'Y':1, 'N':0})
df['Education'] = df['Education'].map({'Graduate': 1, 'Not Graduate': 0})

In [190]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [191]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             614 non-null    int64
 1   Married            614 non-null    int64
 2   Dependents         614 non-null    object
 3   Education          614 non-null    int64
 4   Self_Employed      614 non-null    int64
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         614 non-null    float64
 8   Loan_Amount_Term   614 non-null    float64
 9   Credit_History     614 non-null    float64
 10  Property_Area      614 non-null    object
 11  Loan_Status        614 non-null    int64
dtypes: float64(4), int64(6), object(2)
memory usage: 57.7+ KB

In [192]:
df = pd.get_dummies(df, columns=['Property_Area'])

In [193]:
df = pd.get_dummies(df, columns=['Dependents'])

In [194]:
df.head()

,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Dependents_0,Dependents_1,Dependents_2,Dependents_3+
0,1,0,1,0,5849,0.0,146.412162,360.0,1.0,1,False,False,True,True,False,False,False
1,1,1,1,0,4583,1508.0,128.000000,360.0,1.0,0,True,False,False,False,True,False,False
2,1,1,1,1,3000,0.0,66.000000,360.0,1.0,1,False,False,True,True,False,False,False
3,1,1,0,0,2583,2358.0,120.000000,360.0,1.0,1,False,False,True,True,False,False,False
4,1,0,1,0,6000,0.0,141.000000,360.0,1.0,1,False,False,True,True,False,False,False

In [195]:
df['Property_Area_Rural'] = df['Property_Area_Rural'].astype(int)
df['Property_Area_Semiurban'] = df['Property_Area_Semiurban'].astype(int)
df['Property_Area_Urban'] = df['Property_Area_Urban'].astype(int)

In [196]:
df['Dependents_0'] = df['Dependents_0'].astype(int)
df['Dependents_1'] = df['Dependents_1'].astype(int)
df['Dependents_2'] = df['Dependents_2'].astype(int)
df['Dependents_3+'] = df['Dependents_3+'].astype(int)

In [197]:
df['TotalIncome'] = df['ApplicantIncome'] + df['CoapplicantIncome']

In [198]:
df['Income_Loan_Ratio'] = df['TotalIncome'] / df['LoanAmount']

In [199]:
df['LoanAmount_log'] = np.log(df['LoanAmount'] + 1)

In [200]:
df = df.drop(['ApplicantIncome'], axis=1)
df = df.drop(['CoapplicantIncome'], axis=1)
df = df.drop(['TotalIncome'], axis=1)
df = df.drop(['LoanAmount'], axis=1)

In [201]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   614 non-null    int64
 1   Married                  614 non-null    int64
 2   Education                614 non-null    int64
 3   Self_Employed            614 non-null    int64
 4   Loan_Amount_Term         614 non-null    float64
 5   Credit_History           614 non-null    float64
 6   Loan_Status              614 non-null    int64
 7   Property_Area_Rural      614 non-null    int64
 8   Property_Area_Semiurban  614 non-null    int64
 9   Property_Area_Urban      614 non-null    int64
 10  Dependents_0             614 non-null    int64
 11  Dependents_1             614 non-null    int64
 12  Dependents_2             614 non-null    int64
 13  Dependents_3+            614 non-null    int64
 14  Income_Loan_Ratio        614 non-null    float64
 15  LoanAmount_log           614 non-null    float64
dtypes: float64(4), int64(12)
memory usage: 76.9 KB

In [202]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.preprocessing import StandardScaler

In [203]:
X = df.drop('Loan_Status', axis=1)
y = df['Loan_Status']

In [204]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [205]:
log = LogisticRegression(max_iter=1000, random_state=23)
log_score = cross_val_score(log, X_scaled, y, cv=5, scoring='accuracy')

In [206]:
tree = DecisionTreeClassifier(max_depth=5, random_state=23)
tree_score = cross_val_score(tree, X, y, cv=5, scoring='accuracy')

In [207]:
forest = RandomForestClassifier(n_estimators=100, random_state=23)
forest_score = cross_val_score(forest, X, y, cv=5, scoring='accuracy')

In [208]:
knn = KNeighborsClassifier(n_neighbors=5)
knn_score = cross_val_score(knn, X_scaled, y, cv=5, scoring='accuracy')

In [209]:
print("model_comparision")
print(f"LogisticRegression: {log_score.mean():.3%}")
print(f"DecisionTree: {tree_score.mean():.3%}")
print(f"RandomForest: {forest_score.mean():3%}")
print(f"knn : {knn_score.mean():3%}")

model_comparision
LogisticRegression: 80.782%
DecisionTree: 79.144%
RandomForest: 77.852859%
knn : 75.565774%

In [210]:
from sklearn.model_selection import GridSearchCV

In [211]:
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l2'],
    'solver': ['lbfgs']
}

In [212]:
grid_search = GridSearchCV(LogisticRegression(max_iter=1000),param_grid, cv=5)
grid_search.fit(X_scaled, y)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000),
             param_grid={'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l2'],
                         'solver': ['lbfgs']})

In [213]:
print(grid_search.best_score_)
print(grid_search.best_params_)

0.809462881514061
{'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}